import * as readline from "node:readline";
import { Writable } from "node:stream";
import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { workspaceDir } from "../config.ts";

interface InterviewAnswers {
  userName: string;
  timezone: string;
  roles: string;
  projects: string;
  interactionStyle: string;
}

const QUESTIONS: { key: keyof InterviewAnswers; prompt: string; default?: string }[] = [
  {
    key: "userName",
    prompt: "What should I call you?",
  },
  {
    key: "timezone",
    prompt: "What timezone are you in?",
    default: Intl.DateTimeFormat().resolvedOptions().timeZone,
  },
  {
    key: "roles",
    prompt:
      "What do you do? (e.g., OSS developer, programmer, conference speaker)",
  },
  {
    key: "projects",
    prompt: "What are your main projects or areas of work?",
  },
  {
    key: "interactionStyle",
    prompt:
      "Any preferences for how I interact with you? (e.g., be concise, use Japanese, etc.)",
  },
];

const muted = new Writable({ write(_c, _e, cb) { cb(); } });

function ask(rl: readline.Interface, question: string, defaultValue?: string): Promise<string> {
  const hint = defaultValue ? ` [${defaultValue}]` : "";
  return new Promise((resolve) => {
    rl.question(`${question}${hint}: `, (answer) => {
      resolve(answer.trim() || defaultValue || "");
    });
  });
}

function generateUserMd(a: InterviewAnswers): string {
  return [
    `# USER.md - About Your Human`,
    ``,
    `- **Name:** ${a.userName}`,
    `- **Timezone:** ${a.timezone}`,
    ``,
    `## Context`,
    ``,
    a.roles ? `- **Roles:** ${a.roles}` : "",
    a.projects ? `- **Projects:** ${a.projects}` : "",
    ``,
    a.interactionStyle
      ? [
          `## Interaction preferences`,
          ``,
          a.interactionStyle,
        ].join("\n")
      : "",
    ``,
    `---`,
    `_This file was generated by nyanclaw onboarding. Edit it anytime._`,
    ``,
  ]
    .filter(Boolean)
    .join("\n");
}

/**
 * Detect whether text contains CJK (Chinese/Japanese/Korean) characters.
 */
function containsCjk(text: string): boolean {
  return /[\u3000-\u9FFF\uF900-\uFAFF\uFF00-\uFFEF]/.test(text);
}

/**
 * Determine the dominant language from interview answers.
 * Returns "ja", "ko", "zh", or "en" as a best guess.
 */
function detectLanguage(answers: InterviewAnswers): string {
  const allText = Object.values(answers).join(" ");
  if (containsCjk(allText)) {
    const hiragana = (allText.match(/[\u3040-\u309F]/g) || []).length;
    const katakana = (allText.match(/[\u30A0-\u30FF]/g) || []).length;
    const hangul = (allText.match(/[\uAC00-\uD7AF]/g) || []).length;
    if (hiragana + katakana > hangul) return "ja";
    if (hangul > 0) return "ko";
    return "zh";
  }
  return "en";
}

function generateSoulMd(a: InterviewAnswers): string {
  const lang = detectLanguage(a);
  const langInstruction: Record<string, string> = {
    ja: "デフォルトの会話言語は日本語。ユーザーが他の言語を使った場合はそちらに切り替える。",
    ko: "Default conversation language is Korean. Switch if the user writes in another language.",
    zh: "Default conversation language is Chinese. Switch if the user writes in another language.",
    en: "Default conversation language is English. Switch if the user writes in another language.",
  };

  return [
    `# SOUL.md - Who You Are`,
    ``,
    `You are a practical personal assistant. No unnecessary flattery.`,
    `No filler. Just help.`,
    ``,
    `## Core rules`,
    ``,
    `- **Be helpful, not performative.** Skip "Great question!" — just answer.`,
    `- **Be resourceful.** Read the file, check context, search — ask only when stuck.`,
    `- **Be concise.** Say what's needed, nothing more.`,
    `- ${langInstruction[lang]}`,
    `- **Language detection:** When the user responds in a language, match it.`,
    ``,
    `## Related`,
    ``,
    `- [ADR-0002](../docs/adr/0002-bootstrap-file-system.md)`,
    ``,
  ].join("\n");
}

function isTemplateFile(filePath: string): boolean {
  if (!existsSync(filePath)) return true;
  const content = readFileSync(filePath, "utf-8").trim();
  if (!content) return true;
  // Check if it's the default seed (contains seed marker)
  if (content.includes("Use this file to define the agent") ||
      content.includes("See docs.adr/0002-bootstrap-file-system.md for details")) {
    return true;
  }
  return false;
}

export function needsOnboarding(): boolean {
  const dir = workspaceDir();
  const userMd = join(dir, "USER.md");
  const soulMd = join(dir, "SOUL.md");
  return isTemplateFile(userMd) || isTemplateFile(soulMd);
}

export async function runOnboarding(): Promise<void> {
  const dir = workspaceDir();

  process.stderr.write("\n=== nyanclaw onboarding ===\n");
  process.stderr.write("I'd like to learn a bit about you.\n\n");

  const rl = readline.createInterface({
    input: process.stdin,
    output: muted,
    terminal: true,
  });

  const answers: InterviewAnswers = {
    userName: "",
    timezone: "",
    roles: "",
    projects: "",
    interactionStyle: "",
  };

  for (const q of QUESTIONS) {
    answers[q.key] = await ask(rl, q.prompt, q.default);
  }

  rl.close();

  const userMd = generateUserMd(answers);
  const soulMd = generateSoulMd(answers);

  writeFileSync(join(dir, "USER.md"), userMd, "utf-8");
  writeFileSync(join(dir, "SOUL.md"), soulMd, "utf-8");

  process.stderr.write("\nOnboarding complete. Files created:\n");
  process.stderr.write(`  ${join(dir, "USER.md")}\n`);
  process.stderr.write(`  ${join(dir, "SOUL.md")}\n\n`);
}
