import * as readline from "node:readline";
import { writeFileSync, existsSync, readFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { workspaceDir } from "../config.ts";

interface InterviewAnswers {
  userName: string;
  timezone: string;
  roles: string;
  projects: string;
  interactionStyle: string;
}

const EN_QUESTIONS = [
  { key: "userName" as const, prompt: "What should I call you?" },
  { key: "timezone" as const, prompt: "What timezone are you in?", default: Intl.DateTimeFormat().resolvedOptions().timeZone },
  { key: "roles" as const, prompt: "What do you do? (e.g., OSS developer, programmer, conference speaker)" },
  { key: "projects" as const, prompt: "What are your main projects or areas of work?" },
  { key: "interactionStyle" as const, prompt: "Any preferences for how I interact with you?" },
];

const JA_QUESTIONS = [
  { key: "userName" as const, prompt: "なんと呼べばよいですか" },
  { key: "timezone" as const, prompt: "タイムゾーンはどこですか", default: Intl.DateTimeFormat().resolvedOptions().timeZone },
  { key: "roles" as const, prompt: "どんな活動をしていますか（OSS 開発、プログラマー、登壇など）" },
  { key: "projects" as const, prompt: "主なプロジェクトや取り組みは何ですか" },
  { key: "interactionStyle" as const, prompt: "会話のスタイルについて希望はありますか（簡潔に、日本語で、など）" },
];

function ask(rl: readline.Interface, question: string, defaultValue?: string): Promise<string> {
  const hint = defaultValue ? ` [${defaultValue}]` : "";
  return new Promise((resolve) => {
    rl.question(`\n${question}${hint}: `, (answer) => {
      resolve(answer.trim() || defaultValue || "");
    });
  });
}

function generateUserMd(a: InterviewAnswers): string {
  return [
    `# USER.md - About Your Human`,
    ``,
    `- **Name:** ${a.userName}`,
    `- **Timezone:** ${a.timezone}`,
    ``,
    `## Context`,
    ``,
    a.roles ? `- **Roles:** ${a.roles}` : "",
    a.projects ? `- **Projects:** ${a.projects}` : "",
    ``,
    a.interactionStyle
      ? [
          `## Interaction preferences`,
          ``,
          a.interactionStyle,
        ].join("\n")
      : "",
    ``,
    `---`,
    `_This file was generated by nyanclaw onboarding. Edit it anytime._`,
    ``,
  ]
    .filter(Boolean)
    .join("\n");
}

/**
 * Detect whether text contains CJK (Chinese/Japanese/Korean) characters.
 */
function containsCjk(text: string): boolean {
  return /[\u3000-\u9FFF\uF900-\uFAFF\uFF00-\uFFEF]/.test(text);
}

/**
 * Determine the dominant language from interview answers.
 * Returns "ja", "ko", "zh", or "en" as a best guess.
 */
function detectLanguageFromName(name: string): string {
  if (containsCjk(name)) {
    const hiragana = (name.match(/[\u3040-\u309F]/g) || []).length;
    const katakana = (name.match(/[\u30A0-\u30FF]/g) || []).length;
    const hangul = (name.match(/[\uAC00-\uD7AF]/g) || []).length;
    if (hiragana + katakana > hangul) return "ja";
    if (hangul > 0) return "ko";
    return "zh";
  }
  return "en";
}

function detectLanguage(answers: InterviewAnswers): string {
  const allText = Object.values(answers).join(" ");
  if (containsCjk(allText)) {
    const hiragana = (allText.match(/[\u3040-\u309F]/g) || []).length;
    const katakana = (allText.match(/[\u30A0-\u30FF]/g) || []).length;
    const hangul = (allText.match(/[\uAC00-\uD7AF]/g) || []).length;
    if (hiragana + katakana > hangul) return "ja";
    if (hangul > 0) return "ko";
    return "zh";
  }
  return "en";
}

function generateSoulMd(a: InterviewAnswers): string {
  const lang = detectLanguage(a);
  const langInstruction: Record<string, string> = {
    ja: "デフォルトの会話言語は日本語。ユーザーが他の言語を使った場合はそちらに切り替える。",
    ko: "Default conversation language is Korean. Switch if the user writes in another language.",
    zh: "Default conversation language is Chinese. Switch if the user writes in another language.",
    en: "Default conversation language is English. Switch if the user writes in another language.",
  };

  return [
    `# SOUL.md - Who You Are`,
    ``,
    `You are a practical personal assistant. No unnecessary flattery.`,
    `No filler. Just help.`,
    ``,
    `## Core rules`,
    ``,
    `- **Be helpful, not performative.** Skip "Great question!" — just answer.`,
    `- **Be resourceful.** Read the file, check context, search — ask only when stuck.`,
    `- **Be concise.** Say what's needed, nothing more.`,
    `- ${langInstruction[lang]}`,
    `- **Language detection:** When the user responds in a language, match it.`,
    ``,
    `## Related`,
    ``,
    `- [ADR-0002](../docs/adr/0002-bootstrap-file-system.md)`,
    ``,
  ].join("\n");
}

function isTemplateFile(filePath: string): boolean {
  if (!existsSync(filePath)) return true;
  const content = readFileSync(filePath, "utf-8").trim();
  if (!content) return true;
  // Check if it's the default seed (contains seed marker)
  if (content.includes("Use this file to define the agent") ||
      content.includes("See docs.adr/0002-bootstrap-file-system.md for details")) {
    return true;
  }
  return false;
}

export function needsOnboarding(): boolean {
  const dir = workspaceDir();
  const userMd = join(dir, "USER.md");
  const soulMd = join(dir, "SOUL.md");
  return isTemplateFile(userMd) || isTemplateFile(soulMd);
}

export async function runOnboarding(): Promise<void> {
  const dir = workspaceDir();
  mkdirSync(dir, { recursive: true });

  process.stderr.write("\n=== nyanclaw onboarding ===\n");
  process.stderr.write("I'd like to learn a bit about you.\n\n");

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stderr,
    terminal: true,
  });

  const answers: InterviewAnswers = {
    userName: "",
    timezone: "",
    roles: "",
    projects: "",
    interactionStyle: "",
  };

  // First question always in English to detect language
  answers.userName = await ask(rl, EN_QUESTIONS[0].prompt);
  const lang = detectLanguageFromName(answers.userName);

  const questions = lang === "ja" ? JA_QUESTIONS : EN_QUESTIONS;
  for (let i = 1; i < questions.length; i++) {
    const q = questions[i];
    answers[q.key] = await ask(rl, q.prompt, q.default);
  }

  rl.close();

  const userMd = generateUserMd(answers);
  const soulMd = generateSoulMd(answers);

  writeFileSync(join(dir, "USER.md"), userMd, "utf-8");
  writeFileSync(join(dir, "SOUL.md"), soulMd, "utf-8");

  process.stderr.write("\nOnboarding complete. Files created:\n");
  process.stderr.write(`  ${join(dir, "USER.md")}\n`);
  process.stderr.write(`  ${join(dir, "SOUL.md")}\n\n`);
}
